### PR TITLE
Add alternate parser

### PR DESCRIPTION
**Pull request by vanwagonet**
This adds an alternate parser that according to the benchmark is 8-20x faster on node 0.10. The tests and benchmark have been updated, but the default generated parser has not been replaced.

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by caridy** [comment]
@thetalecrafter, thanks for submitting the PR, we will look at it in details very soon.

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by ericf** [comment]
@thetalecrafter One requirement we have is that the code can run in an ES3 environment without requiring the developer to be using polyfills. What we ended up doing in the other packages is adding a  ["poor man's" shim/sham](https://github.com/yahoo/intl-messageformat/blob/master/src/es5.js) for the ES5 methods we wanted to use in the implementation.

**Comment by thetalecrafter** [comment]
I have removed the ES5 methods.

**Comment by ericf** [comment]
@thetalecrafter cool. I have a few other things I'm working on this week and part of next, but I'll try to get to looking at this more later next week.

**Pull request closed without merging**
